// This file is generated by Firebase Genkit.
'use server';
/**
 * @fileOverview Identifies ingredients from a photo using AI.
 *
 * - identifyIngredientsFromPhoto - A function that handles the ingredient identification process.
 * - IdentifyIngredientsFromPhotoInput - The input type for the identifyIngredientsFromPhoto function.
 * - IdentifyIngredientsFromPhotoOutput - The return type for the identifyIngredientsFromPhoto function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyIngredientsFromPhotoInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of ingredients, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type IdentifyIngredientsFromPhotoInput = z.infer<typeof IdentifyIngredientsFromPhotoInputSchema>;

const IdentifyIngredientsFromPhotoOutputSchema = z.object({
  ingredients: z
    .array(z.string())
    .describe('A list of ingredients identified in the photo.'),
});
export type IdentifyIngredientsFromPhotoOutput = z.infer<typeof IdentifyIngredientsFromPhotoOutputSchema>;

export async function identifyIngredientsFromPhoto(
  input: IdentifyIngredientsFromPhotoInput
): Promise<IdentifyIngredientsFromPhotoOutput> {
  return identifyIngredientsFromPhotoFlow(input);
}

const identifyIngredientsFromPhotoPrompt = ai.definePrompt({
  name: 'identifyIngredientsFromPhotoPrompt',
  input: {schema: IdentifyIngredientsFromPhotoInputSchema},
  output: {schema: IdentifyIngredientsFromPhotoOutputSchema},
  prompt: `You are an expert chef. You will be given a photo of ingredients, and you will identify the ingredients in the photo. Return a list of the ingredients.

Photo: {{media url=photoDataUri}}`,
});

const identifyIngredientsFromPhotoFlow = ai.defineFlow(
  {
    name: 'identifyIngredientsFromPhotoFlow',
    inputSchema: IdentifyIngredientsFromPhotoInputSchema,
    outputSchema: IdentifyIngredientsFromPhotoOutputSchema,
  },
  async input => {
    const {output} = await identifyIngredientsFromPhotoPrompt(input);
    return output!;
  }
);
